### ISSUE TITLE
Missing decref if `sample_clone()` fails in `PathSource::read()`

### ISSUE THREAD

**Issue by stv0g** [VILLASframework/node#665]
https://github.com/VILLASframework/node/blob/13ff7a6e34fb9dcc74246a6278e8379970047892/lib/path_source.cpp#L100

**Comment by PJungkamp** [comment]
This also seems leaky: https://github.com/VILLASframework/node/blob/13ff7a6e34fb9dcc74246a6278e8379970047892/lib/path_source.cpp#L173

Here is the allocation of samples: https://github.com/VILLASframework/node/blob/13ff7a6e34fb9dcc74246a6278e8379970047892/lib/path_source.cpp#L56

Here is the initialization of `recv`: https://github.com/VILLASframework/node/blob/13ff7a6e34fb9dcc74246a6278e8379970047892/lib/path_source.cpp#L61

Shouldn't this `decref` the allocated samples, rather than the received ones?

**Comment by PJungkamp** [comment]
This `return` on mapping failure also leaks, but is probably insignificant: https://github.com/VILLASframework/node/blob/13ff7a6e34fb9dcc74246a6278e8379970047892/lib/path_source.cpp#L121-L123
