### ISSUE TITLE
Format `value` overwrites values

### ISSUE THREAD

**Issue by al3xa23** [VILLASframework/node#720]
Hi, 

I used the format value and discovered values are overwritten except for the last one. The other values are zeros. This occurs if several values are send. 

The pciture shows on the left side the values send from udp socket, and right side, when they are received. 
![format-value](https://github.com/VILLASframework/node/assets/140614263/78276475-f1bd-46ed-940f-a56a6ed24d9f)

**Comment by stv0g** [comment]
Hi @al3xa23,

I am not sure if this is really a bug. Or maybe I dont fully understand the issue which you are facing.

The `value` format is somehow limited in comparison to the other formats which VILLASnode supports.
It only reads/writes a single value (hence the name).

It was introduced for node-types like the MQTT node-type in cases where you publish/subscribe from a MQTT topic on which only a single human-readable value is exchanged (e.g. no JSON or otherwise more complex formatted sample).

**Comment by al3xa23** [comment]
Okay, thanks a lot. Then, I misunderstood the original purpose of the value format.
